spring:
  config:
    activate:
      on-profile: test
name: test
environment: testing
retrofit:
  service:
    url: https://www.google.com

---

spring:
  config:
    activate:
      on-profile: dev
name: dev
environment: development
retrofit:
  service:
    url: https://jsonplaceholder.typicode.com


---

spring:
  config:
    activate:
      on-profile: prod
name: prod
environment: production
retrofit:
  service:
    url: http://frontendshowcase.azurewebsites.net/api/
