spring:
  config:
    activate:
      on-profile: test
name: test
environment: testing
retrofit:
  service:
    url: http://frontendshowcase.azurewebsites.net/api/
executor:
  threadPool:
    maxSize: 3
  timeout:
    duration: 5000
    timeUnit: "MILLISECONDS"
  spring:
    main:
      allow-bean-definition-overriding: true

---

spring:
  config:
    activate:
      on-profile: dev
name: dev
environment: development
retrofit:
  service:
    url: https://jsonplaceholder.typicode.com
executor:
  threadPool:
    maxSize: 3
  timeout:
    duration: 5000
    timeUnit: "MILLISECONDS"
  spring:
    main:
      allow-bean-definition-overriding: true


---

spring:
  config:
    activate:
      on-profile: prod
name: prod
environment: production
retrofit:
  service:
    url: http://frontendshowcase.azurewebsites.net/api/
executor:
  threadPool:
    maxSize: 5
  timeout:
    duration: 10000
    timeUnit: "MILLISECONDS"
  spring:
    main:
      allow-bean-definition-overriding: true